application: applicationname
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

inbound_services:
- channel_presence

derived_file_type:
- python_precompiled

error_handlers:
- file: templates/errors/default_error.html

- error_code: over_quota
  file: templates/errors/over_quota.html

- error_code: dos_api_denial
  file: templates/errors/dos_api_denial.html

- error_code: timeout
  file: templates/errors/timeout.html

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /tasks/.*
  script: main.py
  login: admin

- url: /_ah/queue/deferred
  script: main.py
  login: admin
  
- url: /_ah/stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: main.py